In [ ]:
# Mongo Db ( no sql )
from pymongo import MongoClient

import pandas as pd
import numpy as np

In [ ]:
import csv

with open("nice.txt", mode="r") as f:
    # content = f.read()
    content = f.readlines()
    print(content)

with open("nice.txt", mode="w") as f:
    data = ["Nice\n", "Himal"]
    f.writelines(data)

['Nice\n', 'Himal']

In [ ]:
with open("input.csv", mode="r") as f:
    content = csv.reader(f)
    for value in content:
        print(value)

NameError: name 'csv' is not defined

In [ ]:
with open("input.csv", mode="r") as f:
    content = csv.DictReader(f)

    data = []
    for value in content:
        data.append(value)

NameError: name 'csv' is not defined

In [ ]:
data = [["Name", "Age", "School"], ["Himal", "23", "SBBS"], ["Sajina", "21", "SBBS"]]

with open("output.csv", mode="w") as f:
    writer = csv.writer(f)
    writer.writerows(data)
    writer.writerow(["Baby", "12", "SBNS"])

NameError: name 'csv' is not defined

In [4]:
dictt = [
    {"Name": "Himal", "Age": "34", "School": "Nice"},
    {"Name": "Himal", "Age": "34", "School": "Nice"},
]

with open("output.csv", mode="w") as f:
    content = csv.DictWriter(f, fieldnames=["Name", "Age", "School"])
    content.writerows(dictt)

NameError: name 'csv' is not defined

In [ ]:
# reading and writing on files using pandas
import pandas as pd

content = pd.read_csv("input.csv")
print(content)

      Name  Age School
0    Himal   23   SBBS
1   Sajina   21   SBBS
2   Sajina   22   SBBS
3   Sajina   23   SBBS
4   Sajina   24   SBBS
5   Sajina   25   SBBS
6   Sajina   26   SBBS
7   Sajina   27   SBBS
8   Sajina   28   SBBS
9   Sajina   29   SBBS
10  Sajina   30   SBBS
11  Sajina   31   SBBS
12  Sajina   32   SBBS
13  Sajina   33   SBBS
14  Sajina   34   SBBS
15  Sajina   35   SBBS
16  Sajina   36   SBBS
17  Sajina   37   SBBS
18  Sajina   38   SBBS
19  Sajina   39   SBBS
20  Sajina   40   SBBS
21  Sajina   41   SBBS
22  Sajina   42   SBBS
23  Sajina   43   SBBS
24  Sajina   44   SBBS
25  Sajina   45   SBBS
26  Sajina   46   SBBS
27  Sajina   47   SBBS
28  Sajina   48   SBBS
29  Sajina   49   SBBS
30  Sajina   50   SBBS
31  Sajina   51   SBBS
32  Sajina   52   SBBS
33  Sajina   53   SBBS
34  Sajina   54   SBBS
35  Sajina   55   SBBS
36  Sajina   56   SBBS
37  Sajina   57   SBBS
38  Sajina   58   SBBS
39  Sajina   59   SBBS
40  Sajina   60   SBBS
41  Sajina   61   SBBS

In [ ]:
dataFrame = [
    {"Name": "Himal", "Age": 12},
    {"Name": "Himal", "Age": 12},
    {"Name": "Himal", "Age": 12},
    {"Name": "Himal", "Age": 12},
]

content = pd.DataFrame(dataFrame)
content.to_csv("outputt.csv", index=False)
print(content)

    Name  Age
0  Himal   12
1  Himal   12
2  Himal   12
3  Himal   12

In [ ]:
# reading a json file

import csv
import json
from pprint import pprint

with open("main.json", mode="r") as f:
    content = json.load(f)
    pprint(content)

{'author': '',
 'description': 'This is the code for Chapter 2 of Self Practice',
 'license': 'ISC',
 'main': 'index.js',
 'name': 'Chapter2',
 'scripts': {'test': 'echo "Error: no test specified" && exit 1'},
 'version': '1.0.0'}

In [ ]:
# to write to json file.
data = {"Name": "Himal", "Age": 12}

with open("output.json", mode="w") as f:
    json.dump(data, f, indent=4)
    print("Success")

Success

In [ ]:
# relational databases. using sqlalchemy ( for python direct way )


import sqlite3


connect = sqlite3.connect("example.db")
cursor = connect.cursor()

In [10]:
cursor.execute(
    """
        CREATE TABLE IF NOT EXISTS students(
            id INTEGER PRIMARY KEY,
            name TEXT , 
            age INTEGER
        )
    """
)

In [ ]:
cursor.execute("INSERT INTO students (name , age) VALUES (?,?)", ("Himal", 20))

In [12]:
connect.commit()

In [ ]:
cursor.execute("SELECT * FROM students")
content = cursor.fetchall()
print(content)
for row in content:
    print(row)

[(1, 'Himal', 20), (2, 'Himal', 20), (3, 'Himal', 20)]
(1, 'Himal', 20)
(2, 'Himal', 20)
(3, 'Himal', 20)

In [ ]:
# using sql alchemy
import sqlalchemy


from sqlalchemy import create_engine


engine = create_engine("sqlite:///mydb.db", echo=True)

In [15]:
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, String, Integer


Base = declarative_base()


class Student(Base):
    __tablename__ = "students"
    id = Column(Integer, primary_key=True)
    name = Column(String)
    age = Column(Integer)


Base.metadata.create_all(engine)

2026-02-27 04:58:29,780 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-02-27 04:58:29,781 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("students")
2026-02-27 04:58:29,781 INFO sqlalchemy.engine.Engine [raw sql] ()
2026-02-27 04:58:29,781 INFO sqlalchemy.engine.Engine COMMIT

/tmp/ipykernel_6082/3819995401.py:5: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [16]:
from sqlalchemy.orm import sessionmaker


Session = sessionmaker(bind=engine)
session = Session()

In [ ]:
student1 = Student(name="Himal", age=12)
student2 = Student(name="Sajina", age=12)


session.add(student1)
session.add(student2)
session.commit()

2026-02-27 04:58:29,796 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-02-27 04:58:29,799 INFO sqlalchemy.engine.Engine INSERT INTO students (name, age) VALUES (?, ?) RETURNING id
2026-02-27 04:58:29,799 INFO sqlalchemy.engine.Engine [generated in 0.00009s (insertmanyvalues) 1/2 (ordered; batch not supported)] ('Himal', 12)
2026-02-27 04:58:29,801 INFO sqlalchemy.engine.Engine INSERT INTO students (name, age) VALUES (?, ?) RETURNING id
2026-02-27 04:58:29,801 INFO sqlalchemy.engine.Engine [insertmanyvalues 2/2 (ordered; batch not supported)] ('Sajina', 12)
2026-02-27 04:58:29,803 INFO sqlalchemy.engine.Engine COMMIT

In [18]:
# querying data from the sqlalchemy


students = session.query(Student).all()
print(students)
for student in students:
    print(student.id, student.name, student.age)

2026-02-27 04:58:29,817 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-02-27 04:58:29,819 INFO sqlalchemy.engine.Engine SELECT students.id AS students_id, students.name AS students_name, students.age AS students_age
FROM students
2026-02-27 04:58:29,819 INFO sqlalchemy.engine.Engine [generated in 0.00053s] ()
[<__main__.Student object at 0x7e12ae0a39b0>, <__main__.Student object at 0x7e12ae0a3950>, <__main__.Student object at 0x7e12aed2b440>, <__main__.Student object at 0x7e12e99d27e0>]
1 Himal 12
2 Sajina 12
3 Himal 12
4 Sajina 12

In [19]:
# accessing no sql in python.


from pymongo import MongoClient

client = MongoClient("link")
database = client["school"]
collection = database["students"]

In [20]:
import pandas as pd

for chunk in pd.read_csv("input.csv", chunksize=20):
    chunk.to_csv("output.csv", mode="a")

In [24]:
# merging -> sql ko join jastei ho .
# yesle chai common columns ko aadhar ma join garne kaam garxa.


df1 = pd.DataFrame(
    {"id": [1, 2, 5, 6], "name": ["himal", "Bhandari", "sajina", "baby"]}
)


df2 = pd.DataFrame(
    {"id": [1, 4, 3, 2], "name": ["himal", "Bhandari", "sajina", "baby"]}
)


merge_inner = pd.merge(df1, df2, on="id", how="right")
merge_inner

   id    name_x    name_y
0   1     himal     himal
1   4       NaN  Bhandari
2   3       NaN    sajina
3   2  Bhandari      baby

In [ ]:
import pandas as pd

df1 = pd.DataFrame({"name": ["himal", "Bhandari", "sajina", "baby"]})

df2 = pd.DataFrame({"naam": ["boy", "mgr", "sajina"]})

joined_value = df1.join(df2, how="inner")
joined_value

df_wide = pd.DataFrame(joined_value)

print(df_wide)

       name    naam
0     himal     boy
1  Bhandari     mgr
2    sajina  sajina

In [ ]:
import pandas as pd


df = pd.read_csv("output.csv", encoding="utf-8")

print(df.head(10))


df["Date"] = pd.to_datetime(df["Date"])
df

df["Month"] = df["Date"].dt.to_period("M")
df

monthly_sales = df.groupby("Month")["Age"].sum()
monthly_sales

   Unnamed: 0    Name Age School        Date
0         0.0   Himal  23   SBBS  2023-08-03
1         1.0  Sajina  21   SBBS   2023-08-4
2         2.0  Sajina  22   SBBS   2023-08-5
3         3.0  Sajina  23   SBBS   2023-08-6
4         4.0  Sajina  24   SBBS   2023-08-7
5         5.0  Sajina  25   SBBS   2023-08-8
6         6.0  Sajina  26   SBBS   2023-08-9
7         7.0  Sajina  27   SBBS  2023-08-10
8         8.0  Sajina  28   SBBS  2023-08-11
9         9.0  Sajina  29   SBBS  2023-08-12

Month
2023-08    2321222324252627282930313233343536373839Age404...
2023-09                      484950515253545556575859Age6061
Freq: M, Name: Age, dtype: object

In [2]:
# advanced data wrangling and transformation.

# merging two data frames

import pandas as pd

df1 = pd.DataFrame(
    [
        {"name": "himal", "age": 22},
        {"name": "sajina", "age": 26},
        {"name": "himjin", "age": 25},
        {"name": "bipin", "age": 13},
    ]
)

In [29]:
import pandas as pd

data = {
    "City": ["Kathmandu", "Dharan", "Jhapa"],
    "Age": [20, 34, 35],
}


df1 = pd.DataFrame(data)
print(df1)

        City  Age
0  Kathmandu   20
1     Dharan   34
2      Jhapa   35

In [30]:
data2 = {
    "City": ["Kathmandu", "Binaslu", "Gooday"],
    "Marks": [20, 34, 35],
}


# inner join vaneko intersection ho
# outer join vaneko chai union ho
# left join vaneko ko aadhar ma haalxa.
# right join vaneko right ko aadhar ma hunxa.


df2 = pd.DataFrame(data2)
df2

        City  Marks
0  Kathmandu     20
1    Binaslu     34
2     Gooday     35

In [ ]:
merged_one = pd.merge(df1, df2, on="City", how="inner")
print(merged_one)

        City  Age  Marks
0  Kathmandu   20     20

In [ ]:
union_merged = pd.merge(df1, df2, on="City", how="outer")
print(union_merged)


union_merged.fillna(12)

        City   Age  Marks
0    Binaslu   NaN   34.0
1     Dharan  34.0    NaN
2     Gooday   NaN   35.0
3      Jhapa  35.0    NaN
4  Kathmandu  20.0   20.0

        City   Age  Marks
0    Binaslu  12.0   34.0
1     Dharan  34.0   12.0
2     Gooday  12.0   35.0
3      Jhapa  35.0   12.0
4  Kathmandu  20.0   20.0

In [ ]:
left_join = pd.merge(df1, df2, on="City", how="left")
left_join

        City  Age  Marks
0  Kathmandu   20   20.0
1     Dharan   34    NaN
2      Jhapa   35    NaN

In [ ]:
right_join = pd.merge(df1, df2, on="City", how="right")
print(right_join)

        City   Age  Marks
0  Kathmandu  20.0     20
1    Binaslu   NaN     34
2     Gooday   NaN     35

In [42]:
df_A = pd.DataFrame(
    {
        "Temperature": [20, 30, 45],
    },
    index=["Day1", "Day2", "Day3"],
)

df_B = pd.DataFrame(
    {
        "Marks": [20, 30, 45],
    },
    index=["Day1", "Day2", "Day6"],
)

join_value = df_A.join(df_B, how="inner")
join_value

      Temperature  Marks
Day1           20     20
Day2           30     30

In [46]:
join_right = df_A.join(df_B, how="right")
join_right
join_right.fillna(29)

      Temperature  Marks
Day1         20.0     20
Day2         30.0     30
Day6         29.0     45